/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.88.0
  Forc version: 0.59.0
  Fuel-Core version: 0.26.0
*/

export type { VrfLyncAbi } from './VrfLyncAbi';

export { VrfLyncAbi__factory } from './factories/VrfLyncAbi__factory';
