/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.88.0
  Forc version: 0.59.0
  Fuel-Core version: 0.26.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Option } from "./common";

interface VrfLyncAbiInterface extends Interface {
  functions: {
    get_random_number: FunctionFragment;
    request_random_number: FunctionFragment;
    rng_cost: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'get_random_number', values: [string]): Uint8Array;
  encodeFunctionData(functionFragment: 'request_random_number', values: [string]): Uint8Array;
  encodeFunctionData(functionFragment: 'rng_cost', values: []): Uint8Array;

  decodeFunctionData(functionFragment: 'get_random_number', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'request_random_number', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'rng_cost', data: BytesLike): DecodedValue;
}

export class VrfLyncAbi extends Contract {
  interface: VrfLyncAbiInterface;
  functions: {
    get_random_number: InvokeFunction<[seed: string], Option<string>>;
    request_random_number: InvokeFunction<[seed: string], void>;
    rng_cost: InvokeFunction<[], BN>;
  };
}
